Feature
disc3110/budget-app pull request #1
Opened 2022-04-29 18:06 UTC by disc3110

Created an App with that keeps track of the user's expenses and helps with his budget.
The app consists of three views, a Login Screen, a Category screen, and a Transaction screen.

Here is a briefly explanation of the project: https://www.loom.com/share/b8a15d9415034fa7a7bbccde287c1ae4

Don't forget to change the user and password in config/database.yml, to have some test data `run rails db:seed`

2022-04-29 18:56 UTC, Dipeshtwis requested changes
Hi @disc3110, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

# HIghlights
:+1: The project is deployed online.
:+1: All tests are running. :heavy_check_mark: 

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N.A.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-04-29 18:56 UTC, Dipeshtwis commented on app/views/deals/_deal.html.erb
> +
- [ ] In this page, Please show the date when the transaction happens as per the design.

### Your design
![Screenshot from 2022-04-29 23-57-50](https://user-images.githubusercontent.com/22434660/166008315-7536f567-6aed-43ba-95f0-b81cda43294d.png)


### GIven design
![Screenshot from 2022-04-30 00-16-20](https://user-images.githubusercontent.com/22434660/166008352-3516ca31-ee95-498f-b454-cb0b444830c2.png)

2022-04-29 18:56 UTC, Dipeshtwis commented on app/views/deals/_form.html.erb
> +
- [ ] I would recommend adding the feature to select the `categories` here in the form as per requirements. Please update this.

![Screenshot from 2022-04-30 00-17-18](https://user-images.githubusercontent.com/22434660/166007619-724ba4ad-f7a5-4407-8a23-c33dfc19da61.png)

2022-04-30 00:13 UTC, rukundoeric approved these changes
Hi @disc3110,

_Excellent job on this project. Keep it up 🎆_

_Congratulations! 🎉  on the splendid job 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_


Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

------
>As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-04-30 00:13 UTC, rukundoeric commented on app/views/deals/_deal.html.erb
> +    <p class="fs-075r"><%= deal.created_at.strftime("%d %b %Y")%></p>
- [ ] <b>OPTIONAL:</b> Remember to deploy so that your latest changes can be reflected on your deployed app.

2023-06-09 02:51 UTC, merged